export const data = [
    {
        "name": "Photo 1",
        "url": "/images/desktop_look.jpg",
        "description": "Photo 1 description",
        "date": "2023-01-01",
        "type": "image/jpg",
    },
    {
        "name": "Photo 2",
        "url": "/images/gi.jpg",
        "description": "Photo 1 description",
        "date": "2023-01-01",
        "type": "image/jpg",
    },
    {
        "name": "Photo 3",
        "url": "/images/desktop_look.jpg",
        "description": "Photo 1 description",
        "date": "2023-01-01",
        "type": "image/jpg",
    },
    {
        "name": "Photo 4",
        "url": "/images/desktop_look.jpg",
        "description": "Photo 1 description",
        "date": "2023-01-01",
        "type": "image/jpg",
    },
    {
        "name": "Photo 5",
        "url": "/images/desktop_look.jpg",
        "description": "Photo 1 description",
        "date": "2023-01-01",
        "type": "image/jpg",
    },
    {
        "name": "Photo 6",
        "url": "/images/desktop_look.jpg",
        "description": "Photo 1 description",
        "date": "2023-01-01",
        "type": "image/jpg",
    },
    {
        "name": "Photo 7",
        "url": "/images/desktop_look.jpg",
        "description": "Photo 1 description",
        "date": "2023-01-01",
        "type": "image/jpg",
    },
    {
        "name": "Photo 8",
        "url": "/images/desktop_look.jpg",
        "description": "Photo 1 description",
        "date": "2023-01-01",
        "type": "image/jpg",
    },
    {
        "name": "Photo 9",
        "url": "/images/desktop_look.jpg",
        "description": "Photo 1 description",
        "date": "2023-01-01",
        "type": "image/jpg",
    }
]