export const data = [
    {
        "name": "Photo 1",
        "url": "/images/desktop_look.jpg",
        "description": "Photo 1 description",
        "date": "2023-01-01",
        "type": "image/jpg",
    },
    {
        "name": "Photo 1",
        "url": "/images/desktop_look.jpg",
        "description": "Photo 1 description",
        "date": "2023-01-01",
        "type": "image/jpg",
    },
    {
        "name": "Photo 1",
        "url": "/images/desktop_look.jpg",
        "description": "Photo 1 description",
        "date": "2023-01-01",
        "type": "image/jpg",
    },
    {
        "name": "Photo 1",
        "url": "/images/desktop_look.jpg",
        "description": "Photo 1 description",
        "date": "2023-01-01",
        "type": "image/jpg",
    },
    {
        "name": "Photo 1",
        "url": "/images/desktop_look.jpg",
        "description": "Photo 1 description",
        "date": "2023-01-01",
        "type": "image/jpg",
    },
    {
        "name": "Photo 1",
        "url": "/images/desktop_look.jpg",
        "description": "Photo 1 description",
        "date": "2023-01-01",
        "type": "image/jpg",
    },
    {
        "name": "Photo 1",
        "url": "/images/desktop_look.jpg",
        "description": "Photo 1 description",
        "date": "2023-01-01",
        "type": "image/jpg",
    },
]