export const data = [
    {
        "name": "Photo 1",
        "url": "/images/desktop_look.jpg",
        "description": "Photo 1 description",
        "date": "2023-01-01",
        "type": "image/jpg",
    },
    {
        "name": "Photo 2",
        "url": "/images/girl_in_backpack.jpg",
        "description": "Photo 2 description",
        "date": "2023-01-02",
        "type": "image/jpg",
    },
    {
        "name": "Photo 3",
        "url": "/images/girl_in_black.jpg",
        "description": "Photo 3 description",
        "date": "2023-01-03",
        "type": "image/jpg",
    },
    {
        "name": "Photo 4",
        "url": "/images/kakashi.jpg",
        "description": "Photo 4 description",
        "date": "2023-01-04",
        "type": "image/jpg",
    },
    {
        "name": "Photo 5",
        "url": "/images/man_in_white.jpg",
        "description": "Photo 5 description",
        "date": "2023-01-05",
        "type": "image/jpg",
    },
    {
        "name": "Photo 6",
        "url": "/images/mushroom_guy.jpg",
        "description": "Photo 6 description",
        "date": "2023-01-06",
        "type": "image/jpg",
    },
    {
        "name": "Photo 7",
        "url": "/images/muslim_kids.jpg",
        "description": "Photo 7 description",
        "date": "2023-01-07",
        "type": "image/jpg",
    },
    {
        "name": "Photo 8",
        "url": "/images/naruto.jpg",
        "description": "Photo 8 description",
        "date": "2023-01-08",
        "type": "image/jpg",
    },
    {
        "name": "Photo 9",
        "url": "/images/samurai_.jpg",
        "description": "Photo 1 description",
        "date": "2023-01-01",
        "type": "image/jpg",
    }
]